development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nus_help_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nus_help_test
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nus_help_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock 
